ListenIp="0.0.0.0"
ListenPort=10600

# 主库，读写，优先写
[[Db]]
ServerName="Master"
Host="cim_mysql"
Port=3306
DbName="coffeechat"
UserName="cim"
Password="coffeechat2022"
MaxConnCnt=16

# 从库，只读
# 可以和主库保持一致，这样则意味着不使用主从模式，此时，建议把maxconncnt调小一倍
[[Db]]
ServerName="Slave"
Host="cim_mysql"
Port=3306
DbName="coffeechat"
UserName="cim"
Password="coffeechat2022"
MaxConnCnt=16

#[Kafka]
# Topic由前缀+cmdID组成，如msg_data消息id为301，则Topic=CoffeeChat_301
#TopicPrefix="CoffeeChat_"
#Brokers= ["10.0.59.231:9092"]

[Redis]
Name="cim"
Ip="cim_redis"
Port=6379
KeyPrefix="cim|"        # redis中key的统一前缀
Password="coffeechat"   # redis的密码，不允许为空

[[Redis.Pool]]
Name="unread"
DbNum=1
MaxConnect=64

[[Redis.Pool]]
Name="msgid"            # 消息序号ID
DbNum=2
MaxConnect=16

[[Redis.Pool]]
Name="online_user_hash" # 存储用户在线状态
DbNum=3
MaxConnect=16
